### PR TITLE
chi distributions added to stdlib

### PR DESCRIPTION
**Pull request by maymoo99**

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Why did you close this?

**Comment by maymoo99** [comment]
Sorry, this was unintentional. I was trying to do a pull request within our fork. I will re-open because these changes could be added to the main repo

**Comment by zaxtax** [comment]
On a meta-note, we really ought to get import working so contributions like this can be merged.

**Comment by JacquesCarette** [comment]
Should we really wait until we have `import` to merge this?

**Comment by zaxtax** [comment]
Probably not.

**Pull request merged**
