### PR TITLE
Additional Chi Square tests

### PR DESCRIPTION
**Pull request by staplejw**

### CODE REVIEW

**Comment by staplejw** [comment]
### Failure in: 6:RoundTrip:7:0:t_stdChiSq_superposition:0
haskell/Tests/TestTools.hs:130
expected:
chiSq_iid = fn n nat:
            fn mean real:
            fn stdev prob:
            q <~ plate _ of n: normal(mean, stdev)
            return summate i from 0 to size(q):
                   ((q[i] - mean) * prob2real(1/ stdev)) ^ 2
chi_iid = fn n nat:
          fn mean real:
          fn stdev prob:
          q <~ chiSq_iid(n, mean, stdev)
          return sqrt(real2prob(q))
standardChiSq = fn n nat: chiSq_iid(n, nat2real(0), nat2prob(1))
x <~ standardChiSq(3)
return x
but got:
q309 <~ normal(+0/1, 1/1)
q317 <~ normal(+0/1, 1/1)
q325 <~ normal(+0/1, 1/1)
return q309 ^ 2 + q317 ^ 2 + q325 ^ 2
Cases: 332  Tried: 299  Errors: 3  Failures: 22
                                               
### Failure in: 6:RoundTrip:7:0:t_stdChiSq_superposition:1
haskell/Tests/TestTools.hs:130
expected:
chiSq_iid = fn n nat:
            fn mean real:
            fn stdev prob:
            q <~ plate _ of n: normal(mean, stdev)
            return summate i from 0 to size(q):
                   ((q[i] - mean) * prob2real(1/ stdev)) ^ 2
chi_iid = fn n nat:
          fn mean real:
          fn stdev prob:
          q <~ chiSq_iid(n, mean, stdev)
          return sqrt(real2prob(q))
standardChiSq = fn n nat: chiSq_iid(n, nat2real(0), nat2prob(1))
x <~ standardChiSq(3)
return x
but got:
q90b <~ normal(+0/1, 1/1)
q307 <~ normal(+0/1, 1/1)
q315 <~ normal(+0/1, 1/1)
return q307 ^ 2 + q315 ^ 2 + q90b ^ 2
Cases: 332  Tried: 300  Errors: 3  Failures: 23

**Comment by staplejw** [comment]
### Failure in: 6:RoundTrip:7:1:t_uniform_to_stdChiSq:0
haskell/Tests/TestTools.hs:130
expected:
chiSq_iid = fn n nat:
            fn mean real:
            fn stdev prob:
            q <~ plate _ of n: normal(mean, stdev)
            return summate i from 0 to size(q):
                   ((q[i] - mean) * prob2real(1/ stdev)) ^ 2
chi_iid = fn n nat:
          fn mean real:
          fn stdev prob:
          q <~ chiSq_iid(n, mean, stdev)
          return sqrt(real2prob(q))
standardChiSq = fn n nat: chiSq_iid(n, nat2real(0), nat2prob(1))
standardChiSq(2)
but got:
q307 <~ normal(+0/1, 1/1)
q315 <~ normal(+0/1, 1/1)
return q307 ^ 2 + q315 ^ 2
Cases: 332  Tried: 301  Errors: 3  Failures: 24
                                               
### Failure in: 6:RoundTrip:7:1:t_uniform_to_stdChiSq:1
haskell/Tests/TestTools.hs:130
expected:
chiSq_iid = fn n nat:
            fn mean real:
            fn stdev prob:
            q <~ plate _ of n: normal(mean, stdev)
            return summate i from 0 to size(q):
                   ((q[i] - mean) * prob2real(1/ stdev)) ^ 2
chi_iid = fn n nat:
          fn mean real:
          fn stdev prob:
          q <~ chiSq_iid(n, mean, stdev)
          return sqrt(real2prob(q))
standardChiSq = fn n nat: chiSq_iid(n, nat2real(0), nat2prob(1))
standardChiSq(2)
but got:
x3 <~ uniform(+0/1, +1/1)
return log(real2prob(x3)) * (-2/1)
Cases: 332  Tried: 302  Errors: 3  Failures: 25

**Comment by staplejw** [comment]
### Failure in: 6:RoundTrip:7:2:t_stdChiSq_to_beta:0
haskell/Tests/TestTools.hs:130
expected:
beta(nat2prob(1), nat2prob(2))
but got:
beta(1/1, 2/1)
Cases: 332  Tried: 303  Errors: 3  Failures: 26
                                               
### Failure in: 6:RoundTrip:7:2:t_stdChiSq_to_beta:1
haskell/Tests/TestTools.hs:130
expected:
beta(nat2prob(1), nat2prob(2))
but got:
qd0h <~ normal(+0/1, 1/1)
qd1f <~ normal(+0/1, 1/1)
q30b <~ normal(+0/1, 1/1)
q319 <~ normal(+0/1, 1/1)
q327 <~ normal(+0/1, 1/1)
q335 <~ normal(+0/1, 1/1)
return real2prob
         ((qd0h ^ 2 + qd1f ^ 2)
          / (q30b ^ 2
             + q319 ^ 2
             + q327 ^ 2
             + q335 ^ 2
             + qd0h ^ 2
             + qd1f ^ 2))
Cases: 332  Tried: 304  Errors: 3  Failures: 27

**Comment by JacquesCarette** [comment]
This can't be merged, it introduces a syntax error in `Tests.RoundTrip` !!

**Comment by staplejw** [comment]
I have added the missing line that was causing the error.

**Comment by JacquesCarette** [comment]
There are still problems here.  Those 'expected' answers are not simplified enough, and that is causing parts of the failures.  You'll need to think this through some more.

**Comment by JacquesCarette** [comment]
Are you going to fix the outstanding issues @staplejw ?

**Comment by staplejw** [comment]
Yes, aiming to have this resolved by tomorrow.

**Pull request merged**
