### PR TITLE
addition of 'choose' function 

### PR DESCRIPTION
**Pull request by staplejw**

### CODE REVIEW

**Comment by staplejw** [comment]
There is still the issue of Nat (using Int) vs Natural (using Integer). It is unclear to me how I can get this code to work with arbitrarily large numbers.

**Comment by JacquesCarette** [comment]
Ha, right - I'll look at that soon.

**Comment by JacquesCarette** [comment]
I have merged this in.  It is indeed not the end of the story, as the comments above say.  But it's a start.

**Comment by JacquesCarette** [comment]
Ok, you should merge a39ede2f from master into here. That should make Hakaru's natural numbers use `Natural` (and integers use `Integer`) throughout.

**Pull request merged**
